### ISSUE TITLE
Compiler error: ToBigUint is not implemented for BigUint

### ISSUE THREAD

**Issue by z-tech** [cjayross/miller_rabin#1]
Hey, this package looks sweet and I'm interested in using it for some grad school projects.

I'm newish to Rust and I'm trying to call `is_prime` like I see here in the test suites: https://github.com/cjayross/miller_rabin/blob/master/src/lib.rs#L166

However, I'm getting compiler error, which I'm confused about because it says here BigUint implements ToBigUint: https://docs.rs/num-bigint/0.4.0/num_bigint/struct.BigUint.html#impl-ToBigUint

(also, your test suite seems to do exactly what I'm doing)

    use miller_rabin::{is_prime};
    use num_bigint::{BigUint, RandBigInt};
    
    fn get_prime(size_in_bits: u64) -> BigUint {
        let mut rng = rand::thread_rng();
        let candidate: BigUint = rng.gen_biguint(size_in_bits);
    
        loop {
            if is_prime(&candidate, size_in_bits as usize) {
                        ^^^^^^^^^^ the trait `num_bigint::biguint::ToBigUint` is not implemented for `BigUint`
                return candidate;
            }
            candidate += 1;
        }
    }

Any idea what's up?

UPDATE: my code is here btw: https://github.com/z-tech/tangerine/blob/main/src/lib.rs#L11

**Comment by rj-calvin** [comment]
Huh, this is odd. It has been a while since I messed with this repo (or Rust for that matter). Let me get back to you when I have the time in the upcoming week.

**Comment by z-tech** [comment]
Cool, I appreciate the help. There is definitely no rush 👍
